/**
 * Education dataset.
 *
 * Two degrees (Biology, Computer Science) are modelled course-by-course from
 * the torn wiki tables — every cost, prerequisite, working-stat reward and
 * length in weeks is verified. The remaining ten degrees carry their verified
 * unlocks and perk list, with their course tables flagged `verified: false` so
 * the UI can mark them as incomplete rather than guessing numbers.
 */

export interface Course {
  code: string;
  name: string;
  degree: DegreeCode;
  prereqs: string[];
  cost: number;
  manual: number;
  intelligence: number;
  endurance: number;
  weeks: number;
  unlock?: string;
}

export type DegreeCode =
  | 'BIO'
  | 'BUS'
  | 'CBT'
  | 'CMT'
  | 'GEN'
  | 'HAF'
  | 'HIS'
  | 'LAW'
  | 'MTH'
  | 'PSY'
  | 'DEF'
  | 'SPT';

export interface Degree {
  code: DegreeCode;
  name: string;
  /** Bachelor course code, where known. */
  bachelor?: string;
  /** Verified list of what finishing the degree unlocks / grants. */
  payoff: string[];
  /** Perks spread across the degree's courses. */
  perks: string[];
  verified: boolean;
  courses: Course[];
  courseCount?: number;
  notes?: string;
}

const c = (
  code: string,
  name: string,
  degree: DegreeCode,
  prereqs: string[],
  cost: number,
  manual: number,
  intelligence: number,
  endurance: number,
  weeks: number,
  unlock?: string,
): Course => ({ code, name, degree, prereqs, cost, manual, intelligence, endurance, weeks, unlock });

const BIO_COURSES: Course[] = [
  c('BIO1340', 'Introduction to Biochemistry', 'BIO', [], 200, 5, 50, 5, 1),
  c('BIO2350', 'Evolution', 'BIO', ['BIO1340'], 2_000, 0, 50, 10, 2, '+1% damage bonus to all weapons'),
  c('BIO2360', 'Intermediate Biochemistry', 'BIO', ['BIO1340'], 2_500, 5, 55, 15, 4, '+10% medical item effectiveness'),
  c('BIO2370', 'Advanced Biochemistry', 'BIO', ['BIO1340', 'BIO2360'], 2_750, 0, 65, 10, 4, 'A further +10% medical item effectiveness'),
  c('BIO2380', 'Fundamentals of Neurobiology', 'BIO', ['BIO1340'], 2_800, 0, 65, 15, 3, '+10% damage when hitting an opponent\'s neck'),
  c('BIO2390', 'Chromosomes and Gene Functions', 'BIO', ['BIO1340'], 900, 5, 170, 120, 2),
  c('BIO2400', 'Forensic Science', 'BIO', ['BIO1340'], 3_000, 10, 80, 20, 4, 'Decrease an opponent\'s stealthiness by 0.5'),
  c('BIO2410', 'Anatomy', 'BIO', ['BIO1340'], 3_500, 15, 75, 20, 3, '+3% chance of a critical hit'),
  c('BIO2127', 'Intravenous Therapy', 'BIO', ['BIO1340'], 3_500, 0, 40, 35, 3, 'Withdraw and deliver blood (blood bags)'),
  c('BIO3420', 'Bachelor of Biology', 'BIO', ['BIO1340', 'BIO2350', 'BIO2360', 'BIO2370', 'BIO2380', 'BIO2390', 'BIO2400', 'BIO2410', 'BIO2127'], 5_000, 25, 75, 30, 5, 'Equip life and stat boosters (needles) in your temporary slot'),
];

const CMT_COURSES: Course[] = [
  c('CMT1520', 'Introduction to Computing', 'CMT', [], 200, 0, 45, 50, 1, 'Unlock the Cracking crime · code Simple Viruses'),
  c('CMT2230', 'Web Design And Development', 'CMT', ['CMT1520'], 300, 0, 35, 20, 1, 'Create websites for Bootlegging and Scamming'),
  c('CMT2530', 'Intermediate Programming', 'CMT', ['CMT1520'], 800, 0, 65, 20, 2, 'Code Polymorphic and Tunneling viruses'),
  c('CMT2560', 'Algorithms and Advanced Programming', 'CMT', ['CMT1520', 'CMT2530'], 1_200, 0, 100, 50, 3, 'Code Armored, Stealth and Firewalk viruses'),
  c('CMT2130', 'Web Security and Penetration Testing', 'CMT', ['CMT1520', 'CMT2530'], 1_000, 0, 40, 15, 1, 'Extract email addresses via data breaches (Scamming)'),
  c('CMT2131', 'Automated Data Mining & Processing', 'CMT', ['CMT1520', 'CMT2530'], 1_000, 0, 85, 60, 2, 'Build scrapers to harvest emails from websites'),
  c('CMT2540', 'Networking', 'CMT', ['CMT1520'], 900, 0, 75, 35, 2, 'Gain access to hacking crimes'),
  c('CMT2610', 'Computer Security and Defense', 'CMT', ['CMT1520', 'CMT2540'], 3_200, 0, 175, 55, 4, '+10% hacking crime success rate'),
  c('CMT2550', 'Computer Repair', 'CMT', ['CMT1520'], 850, 25, 90, 55, 2),
  c('CMT2570', 'Fundamentals of Computer Architecture', 'CMT', ['CMT1520'], 1_500, 0, 150, 95, 2, '25% reduction in heat generated by rig components'),
  c('CMT2128', 'Overclocking', 'CMT', ['CMT1520', 'CMT2570'], 500, 0, 25, 15, 1, 'Unlock rig overclocking up to 30%'),
  c('CMT2129', 'Advanced Overclocking', 'CMT', ['CMT1520', 'CMT2570', 'CMT2128'], 500, 0, 30, 20, 1, 'Unlock rig overclocking up to 50%'),
  c('CMT2580', 'Software Engineering', 'CMT', ['CMT1520'], 2_200, 0, 120, 65, 3, '20% decrease in virus coding times'),
  c('CMT2590', 'Quantum Computing', 'CMT', ['CMT1520'], 1_950, 0, 250, 30, 2),
  c('CMT2600', 'Natural Language Engineering', 'CMT', ['CMT1520'], 2_350, 0, 275, 55, 3, '10% decrease in virus coding times'),
  c('CMT3620', 'Bachelor of Computer Science', 'CMT', ['CMT1520', 'CMT2530', 'CMT2560', 'CMT2540', 'CMT2610', 'CMT2550', 'CMT2570', 'CMT2128', 'CMT2129', 'CMT2580', 'CMT2590', 'CMT2600'], 5_000, 0, 115, 25, 7, 'Send mails and cash anonymously'),
];

export const DEGREES: Degree[] = [
  {
    code: 'BIO',
    name: 'Biology',
    bachelor: 'BIO3420',
    verified: true,
    courses: BIO_COURSES,
    payoff: [
      'Equip life and stat boosters (needles) in your temporary slot',
      'Unlocks the Pharmacy on the east side',
      'Best pairing for revivers: Intravenous Therapy + medical effectiveness stacks',
    ],
    perks: [
      '+1% damage with all weapons (Evolution)',
      '+20% total medical item effectiveness (Intermediate + Advanced Biochemistry)',
      '+10% damage on neck hits (Neurobiology)',
      '+3% critical hit chance (Anatomy)',
      'Blood bags usable (Intravenous Therapy)',
    ],
    notes: 'Roughly 31 weeks and $26,150 to finish from scratch — and almost every course is on the recommended early list.',
  },
  {
    code: 'CMT',
    name: 'Computer Science',
    bachelor: 'CMT3620',
    verified: true,
    courses: CMT_COURSES,
    payoff: [
      'Code every virus tier, culminating in Firewalk viruses',
      'Unlock hacking crimes and Cracking',
      'Anonymous mail and cash sending',
      'Rig overclocking up to 50%',
    ],
    perks: [
      '+10% hacking crime success rate',
      '30% total reduction in virus coding times',
      '25% less heat generated by rig components',
      'Unlocks Bootlegging stores and Scamming email tooling',
    ],
    notes: 'The crime-focused degree. Start with CMT1520 (one week) so you can code Simple Viruses in the background for the merit.',
  },
  {
    code: 'BUS',
    name: 'Business Management',
    bachelor: 'BUS3130',
    verified: false,
    courses: [],
    courseCount: 13,
    payoff: [
      'Bachelor of Commerce unlocks new company size, storage size and staff room upgrades',
      'Required to push a company past 5-6 stars',
    ],
    perks: [
      '+1% productivity (MTH2280) / +2% productivity per BUSINESS course (5 courses)',
      'Working-stat package aimed at directors: high manual + intelligence',
    ],
    notes: 'Director-focused. Take it if you own or plan to run a company.',
  },
  {
    code: 'CBT',
    name: 'Combat Training',
    bachelor: 'CBT3870',
    verified: false,
    courses: [],
    courseCount: 12,
    payoff: [
      'Bachelor of Military Arts and Science: start earning weapon experience',
      'Weapon experience raises damage and accuracy for the weapons you actually use',
    ],
    perks: [
      '+1 accuracy with Machine Guns, SMGs, Pistols, Rifles, Shotguns and Heavy Artillery',
      '+1% passive Speed bonus (CBT2790 Military Psychology)',
      '+1% hit rate',
    ],
    notes: 'Weapon experience is the reason to finish this — and it takes 2,000+ hits per weapon to reach 100%.',
  },
  {
    code: 'GEN',
    name: 'General Studies',
    bachelor: 'GEN3121',
    verified: false,
    courses: [],
    courseCount: 8,
    payoff: [
      'Bachelor of General Studies: +10% working stat increase for all further educations completed',
      'Driving-related crime access (Transport Drugs, Arson, GTA)',
    ],
    perks: [
      '+10% working stats from every subsequent course — strongest taken *early*',
      'GEN2119: +5% damage with all temporary weapons',
      'GEN2116: +5% hit increase with all temporary weapons',
    ],
    notes: 'Take GEN1112 and GEN2113 early: they are the cheapest crime-access courses in the game.',
  },
  {
    code: 'HAF',
    name: 'Health & Fitness',
    bachelor: undefined,
    verified: false,
    courses: [],
    courseCount: 11,
    payoff: ['Pure passive battle-stat bonuses bundled with cheap, fast courses'],
    perks: [
      '+3% Strength and +3% Speed (HAF2106/2107/2109)',
      '+2% Dexterity (HAF2104/2108)',
      '+25% speed when defending against an escape attempt (HAF3111)',
    ],
    notes: 'Short courses, permanent passive stat percentages. Almost always worth doing early.',
  },
  {
    code: 'HIS',
    name: 'History',
    bachelor: 'HIS3210',
    verified: false,
    courses: [],
    courseCount: 8,
    payoff: [
      'Unlocks the Museum — exchange plushies, flowers and artifacts for points',
      'Sets of artifacts and collectibles can be swapped at the Museum',
    ],
    perks: [
      '+10% damage with Japanese blade weapons (HIS2160)',
      '+2% bonus to all melee damage (HIS2170)',
    ],
    notes: 'The single most profitable degree for traders: 175 days from scratch before any reductions.',
  },
  {
    code: 'LAW',
    name: 'Law',
    bachelor: undefined,
    verified: false,
    courses: [],
    courseCount: 15,
    payoff: [
      'LAW3102: Busting is 50% easier and bailing is 50% cheaper',
      'Bail yourself and others out while jailed (LAW2900)',
    ],
    perks: [
      '+15% total busting skill (LAW2920 + LAW2970)',
      '15% total bail discount (LAW2930 + LAW2980)',
      'Escape attempts use less nerve and fail less often (LAW2890, LAW2990)',
    ],
    notes: 'Great for faction busting crews and for anyone who gets jailed a lot.',
  },
  {
    code: 'MTH',
    name: 'Mathematics',
    bachelor: 'MTH2320',
    verified: false,
    courses: [],
    courseCount: 11,
    payoff: [
      'Bachelor of Mathematics: 20% ammo conservation',
      'Cheap passive battle stats',
    ],
    perks: [
      '+1% productivity (MTH2280)',
      '+3% Speed (MTH2240/2250) and +3% Defense (MTH2260/2320)',
      '20% ammo management — huge if you burn millions of rounds a month',
    ],
  },
  {
    code: 'PSY',
    name: 'Psychology',
    bachelor: undefined,
    verified: false,
    courses: [],
    courseCount: 7,
    payoff: ['Dexterity-focused passives and crime-success perks'],
    perks: [
      '+15% total passive Dexterity (PSY2640 1%, 2650 2%, 2660 4%, 2670 8%)',
      'Fast, cheap intelligence gains',
    ],
    notes: 'The best passive dexterity package in the game, and only 7 courses deep.',
  },
  {
    code: 'DEF',
    name: 'Self Defense',
    bachelor: undefined,
    verified: false,
    courses: [],
    courseCount: 11,
    payoff: [
      'Unlock the Kick attack (DEF2720 Kick Boxing)',
      'DEF3770: +100% damage increase when fighting with fists alone',
    ],
    perks: [
      '+6% passive Defense (DEF2710/2730/2740)',
      '+5% passive Speed (DEF2750/2760)',
      'Fist-only builds get double damage',
    ],
    notes: 'Roughly 22 weeks and $17,500. Mostly a Defense/Speed package unless you commit to a fists build.',
  },
  {
    code: 'SPT',
    name: 'Sports Science',
    bachelor: undefined,
    verified: false,
    courses: [],
    payoff: [
      'The only degree that directly boosts gym gains',
      'SPT2126 Sports Administration unlocks the Sports Shop (Nikeh Performance)',
    ],
    perks: [
      '+1% gym gain in each of Strength, Speed, Defense and Dexterity (SPT2440-2470)',
      'SPT3510: +1% to all gym gains',
      'SPT2490: +2% passive Speed and Strength · SPT2500: +2% passive Defense and Dexterity',
    ],
    notes: 'If you train every day, this is the highest-value degree in the game. Stack it with Health & Fitness.',
  },
];

export const ALL_COURSES: Course[] = DEGREES.flatMap((d) => d.courses);

export const degreeByCode = (code: DegreeCode): Degree | undefined => DEGREES.find((d) => d.code === code);

export const courseByCode = (code: string): Course | undefined =>
  ALL_COURSES.find((x) => x.code.toUpperCase() === code.toUpperCase());

export function degreeTotals(degree: Degree) {
  const weeks = degree.courses.reduce((sum, x) => sum + x.weeks, 0);
  const cost = degree.courses.reduce((sum, x) => sum + x.cost, 0);
  const manual = degree.courses.reduce((sum, x) => sum + x.manual, 0);
  const intelligence = degree.courses.reduce((sum, x) => sum + x.intelligence, 0);
  const endurance = degree.courses.reduce((sum, x) => sum + x.endurance, 0);
  return { weeks, cost, manual, intelligence, endurance };
}

/** Topological order of a degree's courses (prerequisites first). */
export function courseOrder(degree: Degree): Course[] {
  const remaining = [...degree.courses];
  const done = new Set<string>();
  const out: Course[] = [];
  let guard = 0;
  while (remaining.length && guard < 500) {
    guard += 1;
    const next = remaining.find((course) => course.prereqs.every((p) => done.has(p)));
    if (!next) break;
    out.push(next);
    done.add(next.code);
    remaining.splice(remaining.indexOf(next), 1);
  }
  return out;
}

/**
 * Education time reduction (patch #334, April 2024): reductions are additive,
 * not multiplicative. Merits cap at 20%, WSU stock block 10%, Education
 * principal job 10%. Job points (Fitness Center / Hair Salon) and the Book of
 * Carols shave hours off a course in progress rather than a percentage.
 */
export function reducedWeeks(weeks: number, meritPercent: number, wsu: boolean, principal: boolean): number {
  const reduction = Math.min(20, Math.max(0, meritPercent)) / 100 + (wsu ? 0.1 : 0) + (principal ? 0.1 : 0);
  return Math.max(0, weeks * (1 - Math.min(0.4, reduction)));
}
